// AUTO-GENERATED by fetch_kurs.py
window.KURS_DATA = {
    "rate": 16647.0,
    "date": "10 Desember 2025 - 16 Desember 2025",
    "source": "https://old.beacukai.go.id/websitenewV2/kurs.html"
};
